services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: e-com
    volumes:
      - e-com-svelte-pg-data:/var/lib/postgresql/data

volumes:
  e-com-svelte-pg-data:
    name: e-com-svelte-pg-data
